# Generated by Django 3.2.13 on 2022-06-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='rooms.roomsapplicationmodel', verbose_name='бронируемое жилье'),
            preserve_default=False,
        ),
    ]
