# Generated by Django 3.2.13 on 2022-07-06 12:54

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsapplicationmodel',
            name='photos',
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='photo1',
            field=models.ImageField(blank=True, max_length=255, upload_to=rooms.models.rooms_photo_upload_to, verbose_name='Фото 1'),
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='photo2',
            field=models.ImageField(blank=True, max_length=255, upload_to=rooms.models.rooms_photo_upload_to, verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='photo3',
            field=models.ImageField(blank=True, max_length=255, upload_to=rooms.models.rooms_photo_upload_to, verbose_name='Фото 3'),
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='photo4',
            field=models.ImageField(blank=True, max_length=255, upload_to=rooms.models.rooms_photo_upload_to, verbose_name='Фото 4'),
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='photo5',
            field=models.ImageField(blank=True, max_length=255, upload_to=rooms.models.rooms_photo_upload_to, verbose_name='Фото 5'),
        ),
    ]
