# Generated by Django 3.2.13 on 2022-07-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20220706_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество просмотров'),
        ),
    ]
