# Generated by Django 3.2.13 on 2022-06-30 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_reservation_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='landlord',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='accounts.customcreateuser', verbose_name='имя пользователя'),
            preserve_default=False,
        ),
    ]
