# Generated by Django 3.2.13 on 2022-06-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomsapplicationmodel_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsapplicationmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
    ]
