# Generated by Django 3.2.13 on 2022-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsapplicationmodel',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('отдельная ванная', 'отдельная ванная'), ('отдельная душевая', 'отдельная душевая'), ('общая ванная', 'общая ванная'), ('общая душевая', 'общая душевая'), ('отсутствует', 'отсутствует')], max_length=17, verbose_name='какая у вас ванная комната?'),
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='beds',
            field=models.IntegerField(blank=True, default=1, verbose_name='сколько у вас кроватей?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomsapplicationmodel',
            name='guests',
            field=models.IntegerField(blank=True, default=1, verbose_name='сколько гостей вы готовы принять?'),
            preserve_default=False,
        ),
    ]
