# Generated by Django 3.2.13 on 2022-07-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220716_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsapplicationmodel',
            old_name='housing_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='roomsapplicationmodel',
            old_name='housing_header',
            new_name='header',
        ),
    ]
