# Generated by Django 3.2.13 on 2022-07-01 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_alter_roomsapplicationmodel_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsapplicationmodel',
            name='landlord',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='accounts.customcreateuser', verbose_name='хозяин жилья'),
            preserve_default=False,
        ),
    ]
