# Generated by Django 3.2.13 on 2022-07-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_roomsapplicationmodel_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsapplicationmodel',
            name='owner',
        ),
    ]
