# Generated by Django 3.2.13 on 2022-07-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_rating_ratingstar_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user_review',
            new_name='user',
        ),
    ]
