# Generated by Django 3.2.13 on 2022-07-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20220721_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name_reserv',
            new_name='user',
        ),
    ]
