# Generated by Django 3.2.13 on 2022-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_rename_name_reserv_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_date'], 'verbose_name': 'резерв жилья', 'verbose_name_plural': 'резерв жилья'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='гостей'),
            preserve_default=False,
        ),
    ]
