# Generated by Django 3.2.13 on 2022-08-04 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0011_auto_20220804_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomsApplicationModel',
            new_name='RoomsModel',
        ),
    ]
