# Generated by Django 3.2.13 on 2022-06-30 15:41

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='содержание')),
                ('photo', models.ImageField(blank=True, upload_to=blogs.models.localities_photo_upload_to, verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано ?')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'населенный пункт',
                'verbose_name_plural': 'населенные пункты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InterestingPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='содержание')),
                ('photo', models.ImageField(blank=True, upload_to=blogs.models.intresting_place_photo_upload_to, verbose_name='изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано ?')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogs.localities', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'интересное место',
                'verbose_name_plural': 'интересные места',
                'ordering': ['title'],
            },
        ),
    ]
