# Generated by Django 3.2.13 on 2022-07-16 18:51

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_interestingplaces_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localities',
            name='photo',
        ),
        migrations.CreateModel(
            name='LocalityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=blogs.models.localities_photo_upload_to, verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blogs.localities', verbose_name='населенный пункт')),
            ],
        ),
    ]
