# Generated by Django 3.2.13 on 2022-07-17 11:32

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20220716_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localityimages',
            options={'ordering': ['category'], 'verbose_name': 'изображение населенных пунктов', 'verbose_name_plural': 'изображения населенных пунктов'},
        ),
        migrations.RemoveField(
            model_name='interestingplaces',
            name='photo',
        ),
        migrations.CreateModel(
            name='PlaceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=blogs.models.intresting_place_photo_upload_to, verbose_name='изображение')),
                ('category_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blogs.interestingplaces', verbose_name='место')),
            ],
        ),
    ]
