# Generated by Django 3.2.13 on 2022-07-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20220717_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimages',
            options={'ordering': ['category_place'], 'verbose_name': 'изображение интересного места', 'verbose_name_plural': 'изображения интересных мест'},
        ),
    ]
