# Generated by Django 3.2.13 on 2022-07-17 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_placeimages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimages',
            name='category_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_place', to='blogs.interestingplaces', verbose_name='место'),
        ),
    ]
