# Generated by Django 3.2.13 on 2022-07-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_placeimages_category_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localityimages',
            options={'ordering': ['category'], 'verbose_name': 'изображение населенного пункта', 'verbose_name_plural': 'изображения населенных пунктов'},
        ),
        migrations.AlterField(
            model_name='placeimages',
            name='category_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='blogs.interestingplaces', verbose_name='место'),
        ),
    ]
