# Generated by Django 3.2.13 on 2022-08-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20220717_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestingPlaces',
            new_name='Places',
        ),
    ]
