# Generated by Django 3.2.13 on 2022-07-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rents_apartment',
            field=models.BooleanField(default=False, verbose_name='арендодатель?'),
        ),
    ]
