# Generated by Django 3.2.13 on 2022-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_rents_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=18, unique=True, verbose_name='номер телефона'),
        ),
    ]
